server:
  port: 8887
github:
  client:
    id: c047774e5c90ab0d8ce3
    secret: 78def34915b4cdd5644a9df561b787eefdd3827b
  redirect:
    uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:mysql://192.168.1.98:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.98:9300

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kyrie.community.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  file: logs/community.log
  file.max-history: 15
  file.max-size: 100MB
  level:
    root: info
