package com.kyrie.community.entity;

public class TbComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.parent_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.type
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.like_count
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.content
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_comment.commentator
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long commentator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.id
     *
     * @return the value of community..tb_comment.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.id
     *
     * @param id the value for community..tb_comment.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.parent_id
     *
     * @return the value of community..tb_comment.parent_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.parent_id
     *
     * @param parentId the value for community..tb_comment.parent_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.type
     *
     * @return the value of community..tb_comment.type
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.type
     *
     * @param type the value for community..tb_comment.type
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.gmt_created
     *
     * @return the value of community..tb_comment.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.gmt_created
     *
     * @param gmtCreated the value for community..tb_comment.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.gmt_modified
     *
     * @return the value of community..tb_comment.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.gmt_modified
     *
     * @param gmtModified the value for community..tb_comment.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.like_count
     *
     * @return the value of community..tb_comment.like_count
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.like_count
     *
     * @param likeCount the value for community..tb_comment.like_count
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.content
     *
     * @return the value of community..tb_comment.content
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.content
     *
     * @param content the value for community..tb_comment.content
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_comment.commentator
     *
     * @return the value of community..tb_comment.commentator
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_comment.commentator
     *
     * @param commentator the value for community..tb_comment.commentator
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }
}