package com.kyrie.community.entity;

public class TbNotification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.notifier_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Long notifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.notifier_name
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.receiver_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.outer_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.outer_title
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private String outerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.type
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.status
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_notification.gmt_created
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    private Long gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.id
     *
     * @return the value of community..tb_notification.id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.id
     *
     * @param id the value for community..tb_notification.id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.notifier_id
     *
     * @return the value of community..tb_notification.notifier_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Long getNotifierId() {
        return notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.notifier_id
     *
     * @param notifierId the value for community..tb_notification.notifier_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setNotifierId(Long notifierId) {
        this.notifierId = notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.notifier_name
     *
     * @return the value of community..tb_notification.notifier_name
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.notifier_name
     *
     * @param notifierName the value for community..tb_notification.notifier_name
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.receiver_id
     *
     * @return the value of community..tb_notification.receiver_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.receiver_id
     *
     * @param receiverId the value for community..tb_notification.receiver_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.outer_id
     *
     * @return the value of community..tb_notification.outer_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.outer_id
     *
     * @param outerId the value for community..tb_notification.outer_id
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.outer_title
     *
     * @return the value of community..tb_notification.outer_title
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.outer_title
     *
     * @param outerTitle the value for community..tb_notification.outer_title
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.type
     *
     * @return the value of community..tb_notification.type
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.type
     *
     * @param type the value for community..tb_notification.type
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.status
     *
     * @return the value of community..tb_notification.status
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.status
     *
     * @param status the value for community..tb_notification.status
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_notification.gmt_created
     *
     * @return the value of community..tb_notification.gmt_created
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_notification.gmt_created
     *
     * @param gmtCreated the value for community..tb_notification.gmt_created
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}