package com.kyrie.community.entity;

public class TbQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.title
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.creator_id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.comment_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.view_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.like_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.tag
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.gmt_created
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.gmt_modified
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_question.description
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.id
     *
     * @return the value of community..tb_question.id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.id
     *
     * @param id the value for community..tb_question.id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.title
     *
     * @return the value of community..tb_question.title
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.title
     *
     * @param title the value for community..tb_question.title
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.creator_id
     *
     * @return the value of community..tb_question.creator_id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.creator_id
     *
     * @param creatorId the value for community..tb_question.creator_id
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.comment_count
     *
     * @return the value of community..tb_question.comment_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.comment_count
     *
     * @param commentCount the value for community..tb_question.comment_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.view_count
     *
     * @return the value of community..tb_question.view_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.view_count
     *
     * @param viewCount the value for community..tb_question.view_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.like_count
     *
     * @return the value of community..tb_question.like_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.like_count
     *
     * @param likeCount the value for community..tb_question.like_count
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.tag
     *
     * @return the value of community..tb_question.tag
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.tag
     *
     * @param tag the value for community..tb_question.tag
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.gmt_created
     *
     * @return the value of community..tb_question.gmt_created
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.gmt_created
     *
     * @param gmtCreated the value for community..tb_question.gmt_created
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.gmt_modified
     *
     * @return the value of community..tb_question.gmt_modified
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.gmt_modified
     *
     * @param gmtModified the value for community..tb_question.gmt_modified
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_question.description
     *
     * @return the value of community..tb_question.description
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_question.description
     *
     * @param description the value for community..tb_question.description
     *
     * @mbg.generated Sun Oct 06 09:34:41 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}