package com.kyrie.community.entity;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.account_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.name
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.token
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community..tb_user.avatar_url
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.id
     *
     * @return the value of community..tb_user.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.id
     *
     * @param id the value for community..tb_user.id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.account_id
     *
     * @return the value of community..tb_user.account_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.account_id
     *
     * @param accountId the value for community..tb_user.account_id
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.name
     *
     * @return the value of community..tb_user.name
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.name
     *
     * @param name the value for community..tb_user.name
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.token
     *
     * @return the value of community..tb_user.token
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.token
     *
     * @param token the value for community..tb_user.token
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.gmt_created
     *
     * @return the value of community..tb_user.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.gmt_created
     *
     * @param gmtCreated the value for community..tb_user.gmt_created
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.gmt_modified
     *
     * @return the value of community..tb_user.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.gmt_modified
     *
     * @param gmtModified the value for community..tb_user.gmt_modified
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community..tb_user.avatar_url
     *
     * @return the value of community..tb_user.avatar_url
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community..tb_user.avatar_url
     *
     * @param avatarUrl the value for community..tb_user.avatar_url
     *
     * @mbg.generated Wed Oct 02 14:18:25 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }
}