package com.kyrie.community.mapper;

import com.kyrie.community.entity.TbNotification;
import com.kyrie.community.entity.TbNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    long countByExample(TbNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int deleteByExample(TbNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int insert(TbNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int insertSelective(TbNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    List<TbNotification> selectByExample(TbNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    TbNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbNotification record, @Param("example") TbNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByExample(@Param("record") TbNotification record, @Param("example") TbNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByPrimaryKeySelective(TbNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_notification
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByPrimaryKey(TbNotification record);
}