package com.kyrie.community.mapper;

import com.kyrie.community.entity.TbQuestion;
import com.kyrie.community.entity.TbQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    long countByExample(TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int deleteByExample(TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int insert(TbQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int insertSelective(TbQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    List<TbQuestion> selectByExampleWithBLOBs(TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    List<TbQuestion> selectByExample(TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    TbQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbQuestion record, @Param("example") TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TbQuestion record, @Param("example") TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByExample(@Param("record") TbQuestion record, @Param("example") TbQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByPrimaryKeySelective(TbQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TbQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community..tb_question
     *
     * @mbg.generated Wed Oct 09 19:36:30 CST 2019
     */
    int updateByPrimaryKey(TbQuestion record);
}